spring:
  application:
    name: expense-tracker

server:
  port: 3090

springdoc:
  swagger-ui:
    path: /docs
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /api-docs